# Generated by Django 2.2 on 2020-08-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efemerides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commemoration',
            name='event',
            field=models.CharField(max_length=1000),
        ),
    ]
